project_id = "bwoolbioqpuffhijfjap"

[functions.send-notification-email]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.send-signing-email]
verify_jwt = false

[functions.notify-document-signed]
verify_jwt = false

[functions.send-candidate-invitation]
verify_jwt = false

[functions.seo-proxy]
verify_jwt = false

[functions.seoproxy]
verify_jwt = false

[functions.aeo-audit]
verify_jwt = false
